/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
	"fmt"
)

// checks if the RmaDeleteNoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RmaDeleteNoteRequest{}

// RmaDeleteNoteRequest struct for RmaDeleteNoteRequest
type RmaDeleteNoteRequest struct {
	TenantId             string `json:"tenantId"`
	Id                   string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _RmaDeleteNoteRequest RmaDeleteNoteRequest

// NewRmaDeleteNoteRequest instantiates a new RmaDeleteNoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRmaDeleteNoteRequest(tenantId string, id string) *RmaDeleteNoteRequest {
	this := RmaDeleteNoteRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewRmaDeleteNoteRequestWithDefaults instantiates a new RmaDeleteNoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRmaDeleteNoteRequestWithDefaults() *RmaDeleteNoteRequest {
	this := RmaDeleteNoteRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *RmaDeleteNoteRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *RmaDeleteNoteRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *RmaDeleteNoteRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *RmaDeleteNoteRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RmaDeleteNoteRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RmaDeleteNoteRequest) SetId(v string) {
	o.Id = v
}

func (o RmaDeleteNoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RmaDeleteNoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RmaDeleteNoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRmaDeleteNoteRequest := _RmaDeleteNoteRequest{}

	err = json.Unmarshal(data, &varRmaDeleteNoteRequest)

	if err != nil {
		return err
	}

	*o = RmaDeleteNoteRequest(varRmaDeleteNoteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *RmaDeleteNoteRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *RmaDeleteNoteRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableRmaDeleteNoteRequest struct {
	value *RmaDeleteNoteRequest
	isSet bool
}

func (v NullableRmaDeleteNoteRequest) Get() *RmaDeleteNoteRequest {
	return v.value
}

func (v *NullableRmaDeleteNoteRequest) Set(val *RmaDeleteNoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRmaDeleteNoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRmaDeleteNoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRmaDeleteNoteRequest(val *RmaDeleteNoteRequest) *NullableRmaDeleteNoteRequest {
	return &NullableRmaDeleteNoteRequest{value: val, isSet: true}
}

func (v NullableRmaDeleteNoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRmaDeleteNoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
