/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RmaSetReceivedItemsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RmaSetReceivedItemsRequest{}

// RmaSetReceivedItemsRequest struct for RmaSetReceivedItemsRequest
type RmaSetReceivedItemsRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
	Items []RmaSetReceivedItemsRequestItem `json:"items"`
}

type _RmaSetReceivedItemsRequest RmaSetReceivedItemsRequest

// NewRmaSetReceivedItemsRequest instantiates a new RmaSetReceivedItemsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRmaSetReceivedItemsRequest(tenantId string, id string, items []RmaSetReceivedItemsRequestItem) *RmaSetReceivedItemsRequest {
	this := RmaSetReceivedItemsRequest{}
	this.TenantId = tenantId
	this.Id = id
	this.Items = items
	return &this
}

// NewRmaSetReceivedItemsRequestWithDefaults instantiates a new RmaSetReceivedItemsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRmaSetReceivedItemsRequestWithDefaults() *RmaSetReceivedItemsRequest {
	this := RmaSetReceivedItemsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *RmaSetReceivedItemsRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *RmaSetReceivedItemsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *RmaSetReceivedItemsRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *RmaSetReceivedItemsRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RmaSetReceivedItemsRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RmaSetReceivedItemsRequest) SetId(v string) {
	o.Id = v
}

// GetItems returns the Items field value
func (o *RmaSetReceivedItemsRequest) GetItems() []RmaSetReceivedItemsRequestItem {
	if o == nil {
		var ret []RmaSetReceivedItemsRequestItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RmaSetReceivedItemsRequest) GetItemsOk() ([]RmaSetReceivedItemsRequestItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RmaSetReceivedItemsRequest) SetItems(v []RmaSetReceivedItemsRequestItem) {
	o.Items = v
}

func (o RmaSetReceivedItemsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RmaSetReceivedItemsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *RmaSetReceivedItemsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRmaSetReceivedItemsRequest := _RmaSetReceivedItemsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRmaSetReceivedItemsRequest)

	if err != nil {
		return err
	}

	*o = RmaSetReceivedItemsRequest(varRmaSetReceivedItemsRequest)

	return err
}

type NullableRmaSetReceivedItemsRequest struct {
	value *RmaSetReceivedItemsRequest
	isSet bool
}

func (v NullableRmaSetReceivedItemsRequest) Get() *RmaSetReceivedItemsRequest {
	return v.value
}

func (v *NullableRmaSetReceivedItemsRequest) Set(val *RmaSetReceivedItemsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRmaSetReceivedItemsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRmaSetReceivedItemsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRmaSetReceivedItemsRequest(val *RmaSetReceivedItemsRequest) *NullableRmaSetReceivedItemsRequest {
	return &NullableRmaSetReceivedItemsRequest{value: val, isSet: true}
}

func (v NullableRmaSetReceivedItemsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRmaSetReceivedItemsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


