/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
	"fmt"
)

// RmaCurrency Stands for Albania, not all ;-)
type RmaCurrency string

// List of rmaCurrency
const (
	XXX RmaCurrency = "XXX"
	ALL RmaCurrency = "ALL"
	DZD RmaCurrency = "DZD"
	ARS RmaCurrency = "ARS"
	AUD RmaCurrency = "AUD"
	BSD RmaCurrency = "BSD"
	BHD RmaCurrency = "BHD"
	BDT RmaCurrency = "BDT"
	AMD RmaCurrency = "AMD"
	BBD RmaCurrency = "BBD"
	BMD RmaCurrency = "BMD"
	BTN RmaCurrency = "BTN"
	BOB RmaCurrency = "BOB"
	BWP RmaCurrency = "BWP"
	BZD RmaCurrency = "BZD"
	SBD RmaCurrency = "SBD"
	BND RmaCurrency = "BND"
	MMK RmaCurrency = "MMK"
	BIF RmaCurrency = "BIF"
	KHR RmaCurrency = "KHR"
	CAD RmaCurrency = "CAD"
	CVE RmaCurrency = "CVE"
	KYD RmaCurrency = "KYD"
	LKR RmaCurrency = "LKR"
	CLP RmaCurrency = "CLP"
	CNY RmaCurrency = "CNY"
	COP RmaCurrency = "COP"
	KMF RmaCurrency = "KMF"
	CRC RmaCurrency = "CRC"
	HRK RmaCurrency = "HRK"
	CUP RmaCurrency = "CUP"
	CZK RmaCurrency = "CZK"
	DKK RmaCurrency = "DKK"
	DOP RmaCurrency = "DOP"
	SVC RmaCurrency = "SVC"
	ETB RmaCurrency = "ETB"
	ERN RmaCurrency = "ERN"
	FKP RmaCurrency = "FKP"
	FJD RmaCurrency = "FJD"
	DJF RmaCurrency = "DJF"
	GMD RmaCurrency = "GMD"
	GIP RmaCurrency = "GIP"
	GTQ RmaCurrency = "GTQ"
	GNF RmaCurrency = "GNF"
	GYD RmaCurrency = "GYD"
	HTG RmaCurrency = "HTG"
	HNL RmaCurrency = "HNL"
	HKD RmaCurrency = "HKD"
	HUF RmaCurrency = "HUF"
	ISK RmaCurrency = "ISK"
	INR RmaCurrency = "INR"
	IDR RmaCurrency = "IDR"
	IRR RmaCurrency = "IRR"
	IQD RmaCurrency = "IQD"
	ILS RmaCurrency = "ILS"
	JMD RmaCurrency = "JMD"
	JPY RmaCurrency = "JPY"
	KZT RmaCurrency = "KZT"
	JOD RmaCurrency = "JOD"
	KES RmaCurrency = "KES"
	KPW RmaCurrency = "KPW"
	KRW RmaCurrency = "KRW"
	KWD RmaCurrency = "KWD"
	KGS RmaCurrency = "KGS"
	LAK RmaCurrency = "LAK"
	LBP RmaCurrency = "LBP"
	LSL RmaCurrency = "LSL"
	LRD RmaCurrency = "LRD"
	LYD RmaCurrency = "LYD"
	LTL RmaCurrency = "LTL"
	MOP RmaCurrency = "MOP"
	MWK RmaCurrency = "MWK"
	MYR RmaCurrency = "MYR"
	MVR RmaCurrency = "MVR"
	MRO RmaCurrency = "MRO"
	MUR RmaCurrency = "MUR"
	MXN RmaCurrency = "MXN"
	MNT RmaCurrency = "MNT"
	MDL RmaCurrency = "MDL"
	MAD RmaCurrency = "MAD"
	OMR RmaCurrency = "OMR"
	NAD RmaCurrency = "NAD"
	NPR RmaCurrency = "NPR"
	ANG RmaCurrency = "ANG"
	AWG RmaCurrency = "AWG"
	VUV RmaCurrency = "VUV"
	NZD RmaCurrency = "NZD"
	NIO RmaCurrency = "NIO"
	NGN RmaCurrency = "NGN"
	NOK RmaCurrency = "NOK"
	PKR RmaCurrency = "PKR"
	PAB RmaCurrency = "PAB"
	PGK RmaCurrency = "PGK"
	PYG RmaCurrency = "PYG"
	PEN RmaCurrency = "PEN"
	PHP RmaCurrency = "PHP"
	QAR RmaCurrency = "QAR"
	RUB RmaCurrency = "RUB"
	RWF RmaCurrency = "RWF"
	SHP RmaCurrency = "SHP"
	STD RmaCurrency = "STD"
	SAR RmaCurrency = "SAR"
	SCR RmaCurrency = "SCR"
	SLL RmaCurrency = "SLL"
	SGD RmaCurrency = "SGD"
	VND RmaCurrency = "VND"
	SOS RmaCurrency = "SOS"
	ZAR RmaCurrency = "ZAR"
	SSP RmaCurrency = "SSP"
	SZL RmaCurrency = "SZL"
	SEK RmaCurrency = "SEK"
	CHF RmaCurrency = "CHF"
	SYP RmaCurrency = "SYP"
	THB RmaCurrency = "THB"
	TOP RmaCurrency = "TOP"
	TTD RmaCurrency = "TTD"
	AED RmaCurrency = "AED"
	TND RmaCurrency = "TND"
	UGX RmaCurrency = "UGX"
	MKD RmaCurrency = "MKD"
	EGP RmaCurrency = "EGP"
	GBP RmaCurrency = "GBP"
	TZS RmaCurrency = "TZS"
	USD RmaCurrency = "USD"
	UYU RmaCurrency = "UYU"
	UZS RmaCurrency = "UZS"
	WST RmaCurrency = "WST"
	YER RmaCurrency = "YER"
	TWD RmaCurrency = "TWD"
	CUC RmaCurrency = "CUC"
	ZWL RmaCurrency = "ZWL"
	TMT RmaCurrency = "TMT"
	GHS RmaCurrency = "GHS"
	VEF RmaCurrency = "VEF"
	SDG RmaCurrency = "SDG"
	UYI RmaCurrency = "UYI"
	RSD RmaCurrency = "RSD"
	MZN RmaCurrency = "MZN"
	AZN RmaCurrency = "AZN"
	RON RmaCurrency = "RON"
	CHE RmaCurrency = "CHE"
	CHW RmaCurrency = "CHW"
	TRY RmaCurrency = "TRY"
	XAF RmaCurrency = "XAF"
	XCD RmaCurrency = "XCD"
	XOF RmaCurrency = "XOF"
	XPF RmaCurrency = "XPF"
	XBA RmaCurrency = "XBA"
	XBB RmaCurrency = "XBB"
	XBC RmaCurrency = "XBC"
	XBD RmaCurrency = "XBD"
	XAU RmaCurrency = "XAU"
	XDR RmaCurrency = "XDR"
	XAG RmaCurrency = "XAG"
	XPT RmaCurrency = "XPT"
	XPD RmaCurrency = "XPD"
	XUA RmaCurrency = "XUA"
	ZMW RmaCurrency = "ZMW"
	SRD RmaCurrency = "SRD"
	MGA RmaCurrency = "MGA"
	COU RmaCurrency = "COU"
	AFN RmaCurrency = "AFN"
	TJS RmaCurrency = "TJS"
	AOA RmaCurrency = "AOA"
	BYR RmaCurrency = "BYR"
	BGN RmaCurrency = "BGN"
	CDF RmaCurrency = "CDF"
	BAM RmaCurrency = "BAM"
	EUR RmaCurrency = "EUR"
	MXV RmaCurrency = "MXV"
	UAH RmaCurrency = "UAH"
	GEL RmaCurrency = "GEL"
	BOV RmaCurrency = "BOV"
	PLN RmaCurrency = "PLN"
	BRL RmaCurrency = "BRL"
	CLF RmaCurrency = "CLF"
	XSU RmaCurrency = "XSU"
	USN RmaCurrency = "USN"
)

// All allowed values of RmaCurrency enum
var AllowedRmaCurrencyEnumValues = []RmaCurrency{
	"XXX",
	"ALL",
	"DZD",
	"ARS",
	"AUD",
	"BSD",
	"BHD",
	"BDT",
	"AMD",
	"BBD",
	"BMD",
	"BTN",
	"BOB",
	"BWP",
	"BZD",
	"SBD",
	"BND",
	"MMK",
	"BIF",
	"KHR",
	"CAD",
	"CVE",
	"KYD",
	"LKR",
	"CLP",
	"CNY",
	"COP",
	"KMF",
	"CRC",
	"HRK",
	"CUP",
	"CZK",
	"DKK",
	"DOP",
	"SVC",
	"ETB",
	"ERN",
	"FKP",
	"FJD",
	"DJF",
	"GMD",
	"GIP",
	"GTQ",
	"GNF",
	"GYD",
	"HTG",
	"HNL",
	"HKD",
	"HUF",
	"ISK",
	"INR",
	"IDR",
	"IRR",
	"IQD",
	"ILS",
	"JMD",
	"JPY",
	"KZT",
	"JOD",
	"KES",
	"KPW",
	"KRW",
	"KWD",
	"KGS",
	"LAK",
	"LBP",
	"LSL",
	"LRD",
	"LYD",
	"LTL",
	"MOP",
	"MWK",
	"MYR",
	"MVR",
	"MRO",
	"MUR",
	"MXN",
	"MNT",
	"MDL",
	"MAD",
	"OMR",
	"NAD",
	"NPR",
	"ANG",
	"AWG",
	"VUV",
	"NZD",
	"NIO",
	"NGN",
	"NOK",
	"PKR",
	"PAB",
	"PGK",
	"PYG",
	"PEN",
	"PHP",
	"QAR",
	"RUB",
	"RWF",
	"SHP",
	"STD",
	"SAR",
	"SCR",
	"SLL",
	"SGD",
	"VND",
	"SOS",
	"ZAR",
	"SSP",
	"SZL",
	"SEK",
	"CHF",
	"SYP",
	"THB",
	"TOP",
	"TTD",
	"AED",
	"TND",
	"UGX",
	"MKD",
	"EGP",
	"GBP",
	"TZS",
	"USD",
	"UYU",
	"UZS",
	"WST",
	"YER",
	"TWD",
	"CUC",
	"ZWL",
	"TMT",
	"GHS",
	"VEF",
	"SDG",
	"UYI",
	"RSD",
	"MZN",
	"AZN",
	"RON",
	"CHE",
	"CHW",
	"TRY",
	"XAF",
	"XCD",
	"XOF",
	"XPF",
	"XBA",
	"XBB",
	"XBC",
	"XBD",
	"XAU",
	"XDR",
	"XAG",
	"XPT",
	"XPD",
	"XUA",
	"ZMW",
	"SRD",
	"MGA",
	"COU",
	"AFN",
	"TJS",
	"AOA",
	"BYR",
	"BGN",
	"CDF",
	"BAM",
	"EUR",
	"MXV",
	"UAH",
	"GEL",
	"BOV",
	"PLN",
	"BRL",
	"CLF",
	"XSU",
	"USN",
}

func (v *RmaCurrency) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RmaCurrency(value)
	for _, existing := range AllowedRmaCurrencyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RmaCurrency", value)
}

// NewRmaCurrencyFromValue returns a pointer to a valid RmaCurrency
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRmaCurrencyFromValue(v string) (*RmaCurrency, error) {
	ev := RmaCurrency(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RmaCurrency: valid values are %v", v, AllowedRmaCurrencyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RmaCurrency) IsValid() bool {
	for _, existing := range AllowedRmaCurrencyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to rmaCurrency value
func (v RmaCurrency) Ptr() *RmaCurrency {
	return &v
}

type NullableRmaCurrency struct {
	value *RmaCurrency
	isSet bool
}

func (v NullableRmaCurrency) Get() *RmaCurrency {
	return v.value
}

func (v *NullableRmaCurrency) Set(val *RmaCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableRmaCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableRmaCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRmaCurrency(val *RmaCurrency) *NullableRmaCurrency {
	return &NullableRmaCurrency{value: val, isSet: true}
}

func (v NullableRmaCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRmaCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

