/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
)

// checks if the OrderDataTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDataTotal{}

// OrderDataTotal struct for OrderDataTotal
type OrderDataTotal struct {
	Code *OrderDataTotalCode `json:"code,omitempty"`
	Value *RmaMoney `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderDataTotal OrderDataTotal

// NewOrderDataTotal instantiates a new OrderDataTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDataTotal() *OrderDataTotal {
	this := OrderDataTotal{}
	var code OrderDataTotalCode = ORDERDATATOTALCODE_UNKNOWN
	this.Code = &code
	return &this
}

// NewOrderDataTotalWithDefaults instantiates a new OrderDataTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDataTotalWithDefaults() *OrderDataTotal {
	this := OrderDataTotal{}
	var code OrderDataTotalCode = ORDERDATATOTALCODE_UNKNOWN
	this.Code = &code
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *OrderDataTotal) GetCode() OrderDataTotalCode {
	if o == nil || IsNil(o.Code) {
		var ret OrderDataTotalCode
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDataTotal) GetCodeOk() (*OrderDataTotalCode, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// &#39;Has&#39;Code returns a boolean if a field has been set.
func (o *OrderDataTotal) &#39;Has&#39;Code() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given OrderDataTotalCode and assigns it to the Code field.
func (o *OrderDataTotal) SetCode(v OrderDataTotalCode) {
	o.Code = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OrderDataTotal) GetValue() RmaMoney {
	if o == nil || IsNil(o.Value) {
		var ret RmaMoney
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDataTotal) GetValueOk() (*RmaMoney, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// &#39;Has&#39;Value returns a boolean if a field has been set.
func (o *OrderDataTotal) &#39;Has&#39;Value() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given RmaMoney and assigns it to the Value field.
func (o *OrderDataTotal) SetValue(v RmaMoney) {
	o.Value = &v
}

func (o OrderDataTotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDataTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderDataTotal) UnmarshalJSON(data []byte) (err error) {
	varOrderDataTotal := _OrderDataTotal{}

	err = json.Unmarshal(data, &varOrderDataTotal)

	if err != nil {
		return err
	}

	*o = OrderDataTotal(varOrderDataTotal)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *OrderDataTotal) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *OrderDataTotal) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableOrderDataTotal struct {
	value *OrderDataTotal
	isSet bool
}

func (v NullableOrderDataTotal) Get() *OrderDataTotal {
	return v.value
}

func (v *NullableOrderDataTotal) Set(val *OrderDataTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDataTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDataTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDataTotal(val *OrderDataTotal) *NullableOrderDataTotal {
	return &NullableOrderDataTotal{value: val, isSet: true}
}

func (v NullableOrderDataTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDataTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


