/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateReturnRequestProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateReturnRequestProduct{}

// CreateReturnRequestProduct struct for CreateReturnRequestProduct
type CreateReturnRequestProduct struct {
	Grn string `json:"grn"`
	Quantity string `json:"quantity"`
	Reason *string `json:"reason,omitempty"`
	Note *string `json:"note,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateReturnRequestProduct CreateReturnRequestProduct

// NewCreateReturnRequestProduct instantiates a new CreateReturnRequestProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateReturnRequestProduct(grn string, quantity string) *CreateReturnRequestProduct {
	this := CreateReturnRequestProduct{}
	this.Grn = grn
	this.Quantity = quantity
	return &this
}

// NewCreateReturnRequestProductWithDefaults instantiates a new CreateReturnRequestProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateReturnRequestProductWithDefaults() *CreateReturnRequestProduct {
	this := CreateReturnRequestProduct{}
	return &this
}

// GetGrn returns the Grn field value
func (o *CreateReturnRequestProduct) GetGrn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Grn
}

// GetGrnOk returns a tuple with the Grn field value
// and a boolean to check if the value has been set.
func (o *CreateReturnRequestProduct) GetGrnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grn, true
}

// SetGrn sets field value
func (o *CreateReturnRequestProduct) SetGrn(v string) {
	o.Grn = v
}

// GetQuantity returns the Quantity field value
func (o *CreateReturnRequestProduct) GetQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *CreateReturnRequestProduct) GetQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *CreateReturnRequestProduct) SetQuantity(v string) {
	o.Quantity = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CreateReturnRequestProduct) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReturnRequestProduct) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CreateReturnRequestProduct) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *CreateReturnRequestProduct) SetReason(v string) {
	o.Reason = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *CreateReturnRequestProduct) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReturnRequestProduct) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *CreateReturnRequestProduct) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *CreateReturnRequestProduct) SetNote(v string) {
	o.Note = &v
}

func (o CreateReturnRequestProduct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateReturnRequestProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grn"] = o.Grn
	toSerialize["quantity"] = o.Quantity
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateReturnRequestProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grn",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateReturnRequestProduct := _CreateReturnRequestProduct{}

	err = json.Unmarshal(data, &varCreateReturnRequestProduct)

	if err != nil {
		return err
	}

	*o = CreateReturnRequestProduct(varCreateReturnRequestProduct)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grn")
		delete(additionalProperties, "quantity")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "note")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CreateReturnRequestProduct) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *CreateReturnRequestProduct) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableCreateReturnRequestProduct struct {
	value *CreateReturnRequestProduct
	isSet bool
}

func (v NullableCreateReturnRequestProduct) Get() *CreateReturnRequestProduct {
	return v.value
}

func (v *NullableCreateReturnRequestProduct) Set(val *CreateReturnRequestProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateReturnRequestProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateReturnRequestProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateReturnRequestProduct(val *CreateReturnRequestProduct) *NullableCreateReturnRequestProduct {
	return &NullableCreateReturnRequestProduct{value: val, isSet: true}
}

func (v NullableCreateReturnRequestProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateReturnRequestProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


