/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
	"fmt"
)

// checks if the RmaApproveReturnRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RmaApproveReturnRequest{}

// RmaApproveReturnRequest struct for RmaApproveReturnRequest
type RmaApproveReturnRequest struct {
	TenantId             string                        `json:"tenantId"`
	Id                   string                        `json:"id"`
	RefundShippingCost   bool                          `json:"refundShippingCost"`
	RefundPaymentCost    bool                          `json:"refundPaymentCost"`
	Items                []RmaApproveReturnRequestItem `json:"items"`
	AdditionalProperties map[string]interface{}
}

type _RmaApproveReturnRequest RmaApproveReturnRequest

// NewRmaApproveReturnRequest instantiates a new RmaApproveReturnRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRmaApproveReturnRequest(tenantId string, id string, refundShippingCost bool, refundPaymentCost bool, items []RmaApproveReturnRequestItem) *RmaApproveReturnRequest {
	this := RmaApproveReturnRequest{}
	this.TenantId = tenantId
	this.Id = id
	this.RefundShippingCost = refundShippingCost
	this.RefundPaymentCost = refundPaymentCost
	this.Items = items
	return &this
}

// NewRmaApproveReturnRequestWithDefaults instantiates a new RmaApproveReturnRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRmaApproveReturnRequestWithDefaults() *RmaApproveReturnRequest {
	this := RmaApproveReturnRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *RmaApproveReturnRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *RmaApproveReturnRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *RmaApproveReturnRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *RmaApproveReturnRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RmaApproveReturnRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RmaApproveReturnRequest) SetId(v string) {
	o.Id = v
}

// GetRefundShippingCost returns the RefundShippingCost field value
func (o *RmaApproveReturnRequest) GetRefundShippingCost() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RefundShippingCost
}

// GetRefundShippingCostOk returns a tuple with the RefundShippingCost field value
// and a boolean to check if the value has been set.
func (o *RmaApproveReturnRequest) GetRefundShippingCostOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefundShippingCost, true
}

// SetRefundShippingCost sets field value
func (o *RmaApproveReturnRequest) SetRefundShippingCost(v bool) {
	o.RefundShippingCost = v
}

// GetRefundPaymentCost returns the RefundPaymentCost field value
func (o *RmaApproveReturnRequest) GetRefundPaymentCost() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RefundPaymentCost
}

// GetRefundPaymentCostOk returns a tuple with the RefundPaymentCost field value
// and a boolean to check if the value has been set.
func (o *RmaApproveReturnRequest) GetRefundPaymentCostOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefundPaymentCost, true
}

// SetRefundPaymentCost sets field value
func (o *RmaApproveReturnRequest) SetRefundPaymentCost(v bool) {
	o.RefundPaymentCost = v
}

// GetItems returns the Items field value
func (o *RmaApproveReturnRequest) GetItems() []RmaApproveReturnRequestItem {
	if o == nil {
		var ret []RmaApproveReturnRequestItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RmaApproveReturnRequest) GetItemsOk() ([]RmaApproveReturnRequestItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RmaApproveReturnRequest) SetItems(v []RmaApproveReturnRequestItem) {
	o.Items = v
}

func (o RmaApproveReturnRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RmaApproveReturnRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	toSerialize["refundShippingCost"] = o.RefundShippingCost
	toSerialize["refundPaymentCost"] = o.RefundPaymentCost
	toSerialize["items"] = o.Items

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RmaApproveReturnRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
		"refundShippingCost",
		"refundPaymentCost",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRmaApproveReturnRequest := _RmaApproveReturnRequest{}

	err = json.Unmarshal(data, &varRmaApproveReturnRequest)

	if err != nil {
		return err
	}

	*o = RmaApproveReturnRequest(varRmaApproveReturnRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "refundShippingCost")
		delete(additionalProperties, "refundPaymentCost")
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *RmaApproveReturnRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *RmaApproveReturnRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableRmaApproveReturnRequest struct {
	value *RmaApproveReturnRequest
	isSet bool
}

func (v NullableRmaApproveReturnRequest) Get() *RmaApproveReturnRequest {
	return v.value
}

func (v *NullableRmaApproveReturnRequest) Set(val *RmaApproveReturnRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRmaApproveReturnRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRmaApproveReturnRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRmaApproveReturnRequest(val *RmaApproveReturnRequest) *NullableRmaApproveReturnRequest {
	return &NullableRmaApproveReturnRequest{value: val, isSet: true}
}

func (v NullableRmaApproveReturnRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRmaApproveReturnRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
