/*
RMA Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rma

import (
	"encoding/json"
	"fmt"
)

// checks if the RmaEditNoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RmaEditNoteRequest{}

// RmaEditNoteRequest struct for RmaEditNoteRequest
type RmaEditNoteRequest struct {
	TenantId             string                  `json:"tenantId"`
	Id                   string                  `json:"id"`
	Payload              *EditNoteRequestPayload `json:"payload,omitempty"`
	PayloadMask          *string                 `json:"payloadMask,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RmaEditNoteRequest RmaEditNoteRequest

// NewRmaEditNoteRequest instantiates a new RmaEditNoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRmaEditNoteRequest(tenantId string, id string) *RmaEditNoteRequest {
	this := RmaEditNoteRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewRmaEditNoteRequestWithDefaults instantiates a new RmaEditNoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRmaEditNoteRequestWithDefaults() *RmaEditNoteRequest {
	this := RmaEditNoteRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *RmaEditNoteRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *RmaEditNoteRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *RmaEditNoteRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *RmaEditNoteRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RmaEditNoteRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RmaEditNoteRequest) SetId(v string) {
	o.Id = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *RmaEditNoteRequest) GetPayload() EditNoteRequestPayload {
	if o == nil || IsNil(o.Payload) {
		var ret EditNoteRequestPayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RmaEditNoteRequest) GetPayloadOk() (*EditNoteRequestPayload, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *RmaEditNoteRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given EditNoteRequestPayload and assigns it to the Payload field.
func (o *RmaEditNoteRequest) SetPayload(v EditNoteRequestPayload) {
	o.Payload = &v
}

// GetPayloadMask returns the PayloadMask field value if set, zero value otherwise.
func (o *RmaEditNoteRequest) GetPayloadMask() string {
	if o == nil || IsNil(o.PayloadMask) {
		var ret string
		return ret
	}
	return *o.PayloadMask
}

// GetPayloadMaskOk returns a tuple with the PayloadMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RmaEditNoteRequest) GetPayloadMaskOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadMask) {
		return nil, false
	}
	return o.PayloadMask, true
}

// HasPayloadMask returns a boolean if a field has been set.
func (o *RmaEditNoteRequest) HasPayloadMask() bool {
	if o != nil && !IsNil(o.PayloadMask) {
		return true
	}

	return false
}

// SetPayloadMask gets a reference to the given string and assigns it to the PayloadMask field.
func (o *RmaEditNoteRequest) SetPayloadMask(v string) {
	o.PayloadMask = &v
}

func (o RmaEditNoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RmaEditNoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.PayloadMask) {
		toSerialize["payloadMask"] = o.PayloadMask
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RmaEditNoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRmaEditNoteRequest := _RmaEditNoteRequest{}

	err = json.Unmarshal(data, &varRmaEditNoteRequest)

	if err != nil {
		return err
	}

	*o = RmaEditNoteRequest(varRmaEditNoteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "payload")
		delete(additionalProperties, "payloadMask")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *RmaEditNoteRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *RmaEditNoteRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableRmaEditNoteRequest struct {
	value *RmaEditNoteRequest
	isSet bool
}

func (v NullableRmaEditNoteRequest) Get() *RmaEditNoteRequest {
	return v.value
}

func (v *NullableRmaEditNoteRequest) Set(val *RmaEditNoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRmaEditNoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRmaEditNoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRmaEditNoteRequest(val *RmaEditNoteRequest) *NullableRmaEditNoteRequest {
	return &NullableRmaEditNoteRequest{value: val, isSet: true}
}

func (v NullableRmaEditNoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRmaEditNoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
